image: continuumio/miniconda3:latest

variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"

before_script:
  # conda
  - conda init bash
  - source ~/.bashrc

test:
  stage: test
  except:
    variables:
      - $CI_COMMIT_MESSAGE =~ /skip-test/
  variables:
    CONDA_PKGS_DIRS: "${CI_PROJECT_DIR}/.cache/conda/pkgs"
  cache:
    paths:
      - ".cache/conda/pkgs"
  script:
    - conda env create
    - conda activate kindwise-sdk
    - pip install poetry==1.3.2
    - poetry -vv install

    - pytest -vv
    - black . --check --exclude '(\.cache|venv)'
