name: Tests
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.10"]

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install poetry==1.3.2
        poetry config virtualenvs.create false
        poetry -vv install
    - name: Lint with black
      run: |
        black . --check
    - name: Test with pytest
      run: |
        pytest -vv
      env:
        ENVIRONMENT: PRODUCTION
        PLANT_API_KEY: ${{ secrets.PLANT_API_KEY }}
        INSECT_API_KEY: ${{ secrets.INSECT_API_KEY }}
        MUSHROOM_API_KEY: ${{ secrets.MUSHROOM_API_KEY }}
        CROP_HEALTH_API_KEY: ${{ secrets.CROP_HEALTH_API_KEY }}
